release:
  github:
    owner: azarc-io
    name: vth-faas-sdk-go
  name_template: 'Release {{.Tag}}'
  draft: false

builds:
  - id: module-runner
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    dir: cmd/module-runner
    main: main.go
    binary: module-runner
    env:
      - CGO_ENABLED=0
  - id: spark-web-wrapper
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    dir: cmd/spark-web-wrapper
    main: main.go
    binary: spark-web-wrapper
    env:
      - CGO_ENABLED=0

dockers:
#  - id: linux-arm64
#    ids:
#      - module-runner
#    goos: linux
#    goarch: arm64
#    image_templates:
#      - '{{ .Env.DOCKER_REGISTRY }}:{{ .Tag }}-linux-arm64'
#      - '{{ .Env.DOCKER_REGISTRY }}:latest-linux-arm64'
#    skip_push: "true"
#    build_flag_templates:
#      - --platform=linux/arm64
#    use: buildx
  - id: linux-amd64
    ids:
      - module-runner
      - spark-web-wrapper
    goos: linux
    goarch: amd64
    image_templates:
      - '{{ .Env.DOCKER_REGISTRY }}:{{ .Tag }}-linux-amd64'
      - '{{ .Env.DOCKER_REGISTRY }}:latest-linux-amd64'
#      - 'vth-module-runner:v1.19.1-linux-amd64'
#    skip_push: "true"
    build_flag_templates:
      - --platform=linux/amd64
    use: buildx
  - id: linux-amd64-ubuntu
    ids:
      - module-runner
      - spark-web-wrapper
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.ubuntu
    image_templates:
      - '{{ .Env.DOCKER_REGISTRY }}:{{ .Tag }}-ubuntu-amd64'
      - '{{ .Env.DOCKER_REGISTRY }}:latest-ubuntu-amd64'
    #      - 'vth-module-runner:v1.19.1-linux-amd64'
    #    skip_push: "true"
    build_flag_templates:
      - --platform=linux/amd64
    use: buildx
  - id: linux-arm64-ubuntu
    ids:
      - module-runner
      - spark-web-wrapper
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.ubuntu
    image_templates:
      - '{{ .Env.DOCKER_REGISTRY }}:{{ .Tag }}-ubuntu-arm64'
      - '{{ .Env.DOCKER_REGISTRY }}:latest-ubuntu-arm64'
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    use: buildx

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

checksum:
  name_template: 'SHA256SUMS'
  algorithm: sha256
