release:
  github:
    owner: azarc-io
    name: vth-faas-sdk-go
  name_template: 'Release {{.Tag}}'
  draft: false

builds:
  - skip: true

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

checksum:
  name_template: 'SHA256SUMS'
  algorithm: sha256
