// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: pkg/api/v1/sdk.proto

package sdk_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StageStatus int32

const (
	StageStatus_Pending   StageStatus = 0
	StageStatus_Started   StageStatus = 1
	StageStatus_Completed StageStatus = 2
	StageStatus_Failed    StageStatus = 3
	StageStatus_Skipped   StageStatus = 4
)

// Enum value maps for StageStatus.
var (
	StageStatus_name = map[int32]string{
		0: "Pending",
		1: "Started",
		2: "Completed",
		3: "Failed",
		4: "Skipped",
	}
	StageStatus_value = map[string]int32{
		"Pending":   0,
		"Started":   1,
		"Completed": 2,
		"Failed":    3,
		"Skipped":   4,
	}
)

func (x StageStatus) Enum() *StageStatus {
	p := new(StageStatus)
	*p = x
	return p
}

func (x StageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_sdk_proto_enumTypes[0].Descriptor()
}

func (StageStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_sdk_proto_enumTypes[0]
}

func (x StageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageStatus.Descriptor instead.
func (StageStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{0}
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{0}
}

type Stage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status StageStatus `protobuf:"varint,2,opt,name=status,proto3,enum=sdk_v1.StageStatus" json:"status,omitempty"`
	JobId  string      `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Data   []byte      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Reason string      `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Stage) Reset() {
	*x = Stage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetStatus() StageStatus {
	if x != nil {
		return x.Status
	}
	return StageStatus_Pending
}

func (x *Stage) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Stage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Stage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JobId string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetStageRequest) Reset() {
	*x = GetStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageRequest) ProtoMessage() {}

func (x *GetStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageRequest.ProtoReflect.Descriptor instead.
func (*GetStageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *GetStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStageRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetStageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage *Stage `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
}

func (x *GetStageResponse) Reset() {
	*x = GetStageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageResponse) ProtoMessage() {}

func (x *GetStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageResponse.ProtoReflect.Descriptor instead.
func (*GetStageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *GetStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type SetStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage *Stage `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
}

func (x *SetStageRequest) Reset() {
	*x = SetStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStageRequest) ProtoMessage() {}

func (x *SetStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStageRequest.ProtoReflect.Descriptor instead.
func (*SetStageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *SetStageRequest) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type Variable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value    []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *Variable) Reset() {
	*x = Variable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Variable) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GetVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stage string `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	JobId string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetVariableRequest) Reset() {
	*x = GetVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableRequest) ProtoMessage() {}

func (x *GetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableRequest.ProtoReflect.Descriptor instead.
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{6}
}

func (x *GetVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVariableRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *GetVariableRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetVariableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable *Variable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
}

func (x *GetVariableResponse) Reset() {
	*x = GetVariableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableResponse) ProtoMessage() {}

func (x *GetVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableResponse.ProtoReflect.Descriptor instead.
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{7}
}

func (x *GetVariableResponse) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type SetVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stage    string    `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	JobId    string    `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Variable *Variable `protobuf:"bytes,4,opt,name=variable,proto3" json:"variable,omitempty"`
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{8}
}

func (x *SetVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetVariableRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *SetVariableRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SetVariableRequest) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

var File_pkg_api_v1_sdk_proto protoreflect.FileDescriptor

var file_pkg_api_v1_sdk_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x64, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x22, 0x06,
	0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a,
	0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62,
	0x49, 0x64, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x0f, 0x53,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x55, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x43, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2a, 0x4f, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x10, 0x04, 0x32, 0x88, 0x02, 0x0a, 0x07, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x2e, 0x73,
	0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6b,
	0x5f, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x7a, 0x61, 0x72, 0x63, 0x2d, 0x69, 0x6f, 0x2f, 0x76, 0x74, 0x68, 0x2d,
	0x66, 0x61, 0x61, 0x73, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_v1_sdk_proto_rawDescOnce sync.Once
	file_pkg_api_v1_sdk_proto_rawDescData = file_pkg_api_v1_sdk_proto_rawDesc
)

func file_pkg_api_v1_sdk_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_sdk_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_v1_sdk_proto_rawDescData)
	})
	return file_pkg_api_v1_sdk_proto_rawDescData
}

var file_pkg_api_v1_sdk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_v1_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_v1_sdk_proto_goTypes = []interface{}{
	(StageStatus)(0),            // 0: sdk_v1.StageStatus
	(*Void)(nil),                // 1: sdk_v1.Void
	(*Stage)(nil),               // 2: sdk_v1.Stage
	(*GetStageRequest)(nil),     // 3: sdk_v1.GetStageRequest
	(*GetStageResponse)(nil),    // 4: sdk_v1.GetStageResponse
	(*SetStageRequest)(nil),     // 5: sdk_v1.SetStageRequest
	(*Variable)(nil),            // 6: sdk_v1.Variable
	(*GetVariableRequest)(nil),  // 7: sdk_v1.GetVariableRequest
	(*GetVariableResponse)(nil), // 8: sdk_v1.GetVariableResponse
	(*SetVariableRequest)(nil),  // 9: sdk_v1.SetVariableRequest
}
var file_pkg_api_v1_sdk_proto_depIdxs = []int32{
	0, // 0: sdk_v1.Stage.status:type_name -> sdk_v1.StageStatus
	2, // 1: sdk_v1.GetStageResponse.stage:type_name -> sdk_v1.Stage
	2, // 2: sdk_v1.SetStageRequest.stage:type_name -> sdk_v1.Stage
	6, // 3: sdk_v1.GetVariableResponse.variable:type_name -> sdk_v1.Variable
	6, // 4: sdk_v1.SetVariableRequest.variable:type_name -> sdk_v1.Variable
	3, // 5: sdk_v1.Service.GetStageStatus:input_type -> sdk_v1.GetStageRequest
	5, // 6: sdk_v1.Service.SetStageStatus:input_type -> sdk_v1.SetStageRequest
	7, // 7: sdk_v1.Service.GetVariable:input_type -> sdk_v1.GetVariableRequest
	9, // 8: sdk_v1.Service.SetVariable:input_type -> sdk_v1.SetVariableRequest
	4, // 9: sdk_v1.Service.GetStageStatus:output_type -> sdk_v1.GetStageResponse
	1, // 10: sdk_v1.Service.SetStageStatus:output_type -> sdk_v1.Void
	8, // 11: sdk_v1.Service.GetVariable:output_type -> sdk_v1.GetVariableResponse
	1, // 12: sdk_v1.Service.SetVariable:output_type -> sdk_v1.Void
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_sdk_proto_init() }
func file_pkg_api_v1_sdk_proto_init() {
	if File_pkg_api_v1_sdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_v1_sdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Variable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVariableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_v1_sdk_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_sdk_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_sdk_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_sdk_proto_enumTypes,
		MessageInfos:      file_pkg_api_v1_sdk_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_sdk_proto = out.File
	file_pkg_api_v1_sdk_proto_rawDesc = nil
	file_pkg_api_v1_sdk_proto_goTypes = nil
	file_pkg_api_v1_sdk_proto_depIdxs = nil
}
