// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: pkg/api/v1/sdk.proto

package sdk_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	ErrorType_Failed   ErrorType = 0
	ErrorType_Canceled ErrorType = 1
	ErrorType_Skip     ErrorType = 2
	ErrorType_Retry    ErrorType = 3
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "Failed",
		1: "Canceled",
		2: "Skip",
		3: "Retry",
	}
	ErrorType_value = map[string]int32{
		"Failed":   0,
		"Canceled": 1,
		"Skip":     2,
		"Retry":    3,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_sdk_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_sdk_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{0}
}

type StageStatus int32

const (
	StageStatus_StagePending   StageStatus = 0
	StageStatus_StageStarted   StageStatus = 1
	StageStatus_StageCompleted StageStatus = 2
	StageStatus_StageFailed    StageStatus = 3
	StageStatus_StageSkipped   StageStatus = 4
	StageStatus_StageCanceled  StageStatus = 5
)

// Enum value maps for StageStatus.
var (
	StageStatus_name = map[int32]string{
		0: "StagePending",
		1: "StageStarted",
		2: "StageCompleted",
		3: "StageFailed",
		4: "StageSkipped",
		5: "StageCanceled",
	}
	StageStatus_value = map[string]int32{
		"StagePending":   0,
		"StageStarted":   1,
		"StageCompleted": 2,
		"StageFailed":    3,
		"StageSkipped":   4,
		"StageCanceled":  5,
	}
)

func (x StageStatus) Enum() *StageStatus {
	p := new(StageStatus)
	*p = x
	return p
}

func (x StageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_sdk_proto_enumTypes[1].Descriptor()
}

func (StageStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_sdk_proto_enumTypes[1]
}

func (x StageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageStatus.Descriptor instead.
func (StageStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{1}
}

type JobStatus int32

const (
	JobStatus_JobWaiting                    JobStatus = 0
	JobStatus_JobRunning                    JobStatus = 1
	JobStatus_JobDone                       JobStatus = 2
	JobStatus_JobCanceled                   JobStatus = 3
	JobStatus_JobCompletionStarted          JobStatus = 4
	JobStatus_JobCompletionDone             JobStatus = 5
	JobStatus_JobCompletionDoneWithErrors   JobStatus = 6
	JobStatus_JobCompensationStarted        JobStatus = 7
	JobStatus_JobCompensationDone           JobStatus = 8
	JobStatus_JobCompensationDoneWithErrors JobStatus = 9
	JobStatus_JobCancellationStarted        JobStatus = 10
	JobStatus_JobCancellationDone           JobStatus = 11
	JobStatus_JobCancellationDoneWithErrors JobStatus = 12
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0:  "JobWaiting",
		1:  "JobRunning",
		2:  "JobDone",
		3:  "JobCanceled",
		4:  "JobCompletionStarted",
		5:  "JobCompletionDone",
		6:  "JobCompletionDoneWithErrors",
		7:  "JobCompensationStarted",
		8:  "JobCompensationDone",
		9:  "JobCompensationDoneWithErrors",
		10: "JobCancellationStarted",
		11: "JobCancellationDone",
		12: "JobCancellationDoneWithErrors",
	}
	JobStatus_value = map[string]int32{
		"JobWaiting":                    0,
		"JobRunning":                    1,
		"JobDone":                       2,
		"JobCanceled":                   3,
		"JobCompletionStarted":          4,
		"JobCompletionDone":             5,
		"JobCompletionDoneWithErrors":   6,
		"JobCompensationStarted":        7,
		"JobCompensationDone":           8,
		"JobCompensationDoneWithErrors": 9,
		"JobCancellationStarted":        10,
		"JobCancellationDone":           11,
		"JobCancellationDoneWithErrors": 12,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_sdk_proto_enumTypes[2].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_sdk_proto_enumTypes[2]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{2}
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode uint32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorType ErrorType `protobuf:"varint,3,opt,name=error_type,json=errorType,proto3,enum=sdk_v1.ErrorType" json:"error_type,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Error) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Error) GetErrorType() ErrorType {
	if x != nil {
		return x.ErrorType
	}
	return ErrorType_Failed
}

type ExecuteJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key              string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TransactionId    string      `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CorrelationId    string      `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	LastActiveStage  string      `protobuf:"bytes,4,opt,name=last_active_stage,json=lastActiveStage,proto3" json:"last_active_stage,omitempty"`
	LastActiveStatus StageStatus `protobuf:"varint,5,opt,name=last_active_status,json=lastActiveStatus,proto3,enum=sdk_v1.StageStatus" json:"last_active_status,omitempty"`
}

func (x *ExecuteJobRequest) Reset() {
	*x = ExecuteJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteJobRequest) ProtoMessage() {}

func (x *ExecuteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteJobRequest.ProtoReflect.Descriptor instead.
func (*ExecuteJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteJobRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExecuteJobRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ExecuteJobRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ExecuteJobRequest) GetLastActiveStage() string {
	if x != nil {
		return x.LastActiveStage
	}
	return ""
}

func (x *ExecuteJobRequest) GetLastActiveStatus() StageStatus {
	if x != nil {
		return x.LastActiveStatus
	}
	return StageStatus_StagePending
}

type SetJobStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Status JobStatus `protobuf:"varint,2,opt,name=status,proto3,enum=sdk_v1.JobStatus" json:"status,omitempty"`
	Err    *Error    `protobuf:"bytes,3,opt,name=err,proto3,oneof" json:"err,omitempty"`
}

func (x *SetJobStatusRequest) Reset() {
	*x = SetJobStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobStatusRequest) ProtoMessage() {}

func (x *SetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*SetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *SetJobStatusRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetJobStatusRequest) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JobWaiting
}

func (x *SetJobStatusRequest) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type RegisterHeartbeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobKeys []string `protobuf:"bytes,1,rep,name=job_keys,json=jobKeys,proto3" json:"job_keys,omitempty"`
}

func (x *RegisterHeartbeatsRequest) Reset() {
	*x = RegisterHeartbeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterHeartbeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHeartbeatsRequest) ProtoMessage() {}

func (x *RegisterHeartbeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHeartbeatsRequest.ProtoReflect.Descriptor instead.
func (*RegisterHeartbeatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterHeartbeatsRequest) GetJobKeys() []string {
	if x != nil {
		return x.JobKeys
	}
	return nil
}

type StageResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *structpb.Value `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StageResult) Reset() {
	*x = StageResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageResult) ProtoMessage() {}

func (x *StageResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageResult.ProtoReflect.Descriptor instead.
func (*StageResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *StageResult) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetStageStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JobKey string      `protobuf:"bytes,2,opt,name=job_key,json=jobKey,proto3" json:"job_key,omitempty"`
	Status StageStatus `protobuf:"varint,3,opt,name=status,proto3,enum=sdk_v1.StageStatus" json:"status,omitempty"`
	Err    *Error      `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *SetStageStatusRequest) Reset() {
	*x = SetStageStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStageStatusRequest) ProtoMessage() {}

func (x *SetStageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStageStatusRequest.ProtoReflect.Descriptor instead.
func (*SetStageStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{6}
}

func (x *SetStageStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetStageStatusRequest) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

func (x *SetStageStatusRequest) GetStatus() StageStatus {
	if x != nil {
		return x.Status
	}
	return StageStatus_StagePending
}

func (x *SetStageStatusRequest) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type GetStageResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JobKey string `protobuf:"bytes,2,opt,name=job_key,json=jobKey,proto3" json:"job_key,omitempty"`
}

func (x *GetStageResultRequest) Reset() {
	*x = GetStageResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageResultRequest) ProtoMessage() {}

func (x *GetStageResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageResultRequest.ProtoReflect.Descriptor instead.
func (*GetStageResultRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{7}
}

func (x *GetStageResultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStageResultRequest) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

type GetStageResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *StageResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetStageResultResponse) Reset() {
	*x = GetStageResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageResultResponse) ProtoMessage() {}

func (x *GetStageResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageResultResponse.ProtoReflect.Descriptor instead.
func (*GetStageResultResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{8}
}

func (x *GetStageResultResponse) GetResult() *StageResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type SetStageResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobKey string       `protobuf:"bytes,1,opt,name=job_key,json=jobKey,proto3" json:"job_key,omitempty"`
	Name   string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Result *StageResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetStageResultRequest) Reset() {
	*x = SetStageResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStageResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStageResultRequest) ProtoMessage() {}

func (x *SetStageResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStageResultRequest.ProtoReflect.Descriptor instead.
func (*SetStageResultRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{9}
}

func (x *SetStageResultRequest) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

func (x *SetStageResultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetStageResultRequest) GetResult() *StageResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetStageStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobKey string `protobuf:"bytes,1,opt,name=job_key,json=jobKey,proto3" json:"job_key,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetStageStatusRequest) Reset() {
	*x = GetStageStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageStatusRequest) ProtoMessage() {}

func (x *GetStageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStageStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{10}
}

func (x *GetStageStatusRequest) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

func (x *GetStageStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetStageStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status StageStatus `protobuf:"varint,1,opt,name=status,proto3,enum=sdk_v1.StageStatus" json:"status,omitempty"`
}

func (x *GetStageStatusResponse) Reset() {
	*x = GetStageStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageStatusResponse) ProtoMessage() {}

func (x *GetStageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStageStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{11}
}

func (x *GetStageStatusResponse) GetStatus() StageStatus {
	if x != nil {
		return x.Status
	}
	return StageStatus_StagePending
}

type Variable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value    *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	MimeType string          `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *Variable) Reset() {
	*x = Variable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{12}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Variable) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GetVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stage  string `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	JobKey string `protobuf:"bytes,3,opt,name=job_key,json=jobKey,proto3" json:"job_key,omitempty"`
}

func (x *GetVariableRequest) Reset() {
	*x = GetVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableRequest) ProtoMessage() {}

func (x *GetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableRequest.ProtoReflect.Descriptor instead.
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{13}
}

func (x *GetVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVariableRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *GetVariableRequest) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

type GetVariableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable *Variable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
}

func (x *GetVariableResponse) Reset() {
	*x = GetVariableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableResponse) ProtoMessage() {}

func (x *GetVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableResponse.ProtoReflect.Descriptor instead.
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{14}
}

func (x *GetVariableResponse) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type SetVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stage    string    `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	JobKey   string    `protobuf:"bytes,3,opt,name=job_key,json=jobKey,proto3" json:"job_key,omitempty"`
	Variable *Variable `protobuf:"bytes,4,opt,name=variable,proto3" json:"variable,omitempty"`
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1_sdk_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_sdk_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_sdk_proto_rawDescGZIP(), []int{15}
}

func (x *SetVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetVariableRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *SetVariableRequest) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

func (x *SetVariableRequest) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

var File_pkg_api_v1_sdk_proto protoreflect.FileDescriptor

var file_pkg_api_v1_sdk_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x64, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x06, 0x0a, 0x04,
	0x56, 0x6f, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x22, 0xe2, 0x01, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x13, 0x53, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x64,
	0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72, 0x22, 0x36, 0x0a, 0x19,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62,
	0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62,
	0x4b, 0x65, 0x79, 0x73, 0x22, 0x39, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x92, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x6a, 0x6f, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6a, 0x6f, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x22, 0x44, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6a, 0x6f, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x45, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x71, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6a, 0x6f,
	0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x6f, 0x62,
	0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x44, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x6a, 0x6f, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6a, 0x6f, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x69, 0x0a, 0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x57, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x6a, 0x6f, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a,
	0x6f, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x43, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x12, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6a,
	0x6f, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x6f,
	0x62, 0x4b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x2a, 0x3a, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x6b, 0x69,
	0x70, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x74, 0x72, 0x79, 0x10, 0x03, 0x2a, 0x7b,
	0x0a, 0x0b, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x74, 0x61, 0x67, 0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x67, 0x65, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53,
	0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x10, 0x05, 0x2a, 0xcb, 0x02, 0x0a, 0x09,
	0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x4a, 0x6f, 0x62,
	0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4a, 0x6f, 0x62,
	0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4a, 0x6f, 0x62,
	0x44, 0x6f, 0x6e, 0x65, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x4a, 0x6f, 0x62, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10,
	0x04, 0x12, 0x15, 0x0a, 0x11, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x10, 0x05, 0x12, 0x1f, 0x0a, 0x1b, 0x4a, 0x6f, 0x62, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x10, 0x06, 0x12, 0x1a, 0x0a, 0x16, 0x4a, 0x6f, 0x62,
	0x43, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x10, 0x07, 0x12, 0x17, 0x0a, 0x13, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70,
	0x65, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x10, 0x08, 0x12, 0x21,
	0x0a, 0x1d, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x10,
	0x09, 0x12, 0x1a, 0x0a, 0x16, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x0a, 0x12, 0x17, 0x0a,
	0x13, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x6f, 0x6e, 0x65, 0x10, 0x0b, 0x12, 0x21, 0x0a, 0x1d, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x10, 0x0c, 0x32, 0x45, 0x0a, 0x0c, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x19, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x32, 0xb3, 0x04, 0x0a, 0x0e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6b,
	0x5f, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12,
	0x45, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x64, 0x6b, 0x5f, 0x76,
	0x31, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x7a, 0x61, 0x72, 0x63, 0x2d, 0x69, 0x6f, 0x2f, 0x76, 0x74,
	0x68, 0x2d, 0x66, 0x61, 0x61, 0x73, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_v1_sdk_proto_rawDescOnce sync.Once
	file_pkg_api_v1_sdk_proto_rawDescData = file_pkg_api_v1_sdk_proto_rawDesc
)

func file_pkg_api_v1_sdk_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_sdk_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_v1_sdk_proto_rawDescData)
	})
	return file_pkg_api_v1_sdk_proto_rawDescData
}

var file_pkg_api_v1_sdk_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_api_v1_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_api_v1_sdk_proto_goTypes = []interface{}{
	(ErrorType)(0),                    // 0: sdk_v1.ErrorType
	(StageStatus)(0),                  // 1: sdk_v1.StageStatus
	(JobStatus)(0),                    // 2: sdk_v1.JobStatus
	(*Void)(nil),                      // 3: sdk_v1.Void
	(*Error)(nil),                     // 4: sdk_v1.Error
	(*ExecuteJobRequest)(nil),         // 5: sdk_v1.ExecuteJobRequest
	(*SetJobStatusRequest)(nil),       // 6: sdk_v1.SetJobStatusRequest
	(*RegisterHeartbeatsRequest)(nil), // 7: sdk_v1.RegisterHeartbeatsRequest
	(*StageResult)(nil),               // 8: sdk_v1.StageResult
	(*SetStageStatusRequest)(nil),     // 9: sdk_v1.SetStageStatusRequest
	(*GetStageResultRequest)(nil),     // 10: sdk_v1.GetStageResultRequest
	(*GetStageResultResponse)(nil),    // 11: sdk_v1.GetStageResultResponse
	(*SetStageResultRequest)(nil),     // 12: sdk_v1.SetStageResultRequest
	(*GetStageStatusRequest)(nil),     // 13: sdk_v1.GetStageStatusRequest
	(*GetStageStatusResponse)(nil),    // 14: sdk_v1.GetStageStatusResponse
	(*Variable)(nil),                  // 15: sdk_v1.Variable
	(*GetVariableRequest)(nil),        // 16: sdk_v1.GetVariableRequest
	(*GetVariableResponse)(nil),       // 17: sdk_v1.GetVariableResponse
	(*SetVariableRequest)(nil),        // 18: sdk_v1.SetVariableRequest
	(*structpb.Value)(nil),            // 19: google.protobuf.Value
}
var file_pkg_api_v1_sdk_proto_depIdxs = []int32{
	0,  // 0: sdk_v1.Error.error_type:type_name -> sdk_v1.ErrorType
	1,  // 1: sdk_v1.ExecuteJobRequest.last_active_status:type_name -> sdk_v1.StageStatus
	2,  // 2: sdk_v1.SetJobStatusRequest.status:type_name -> sdk_v1.JobStatus
	4,  // 3: sdk_v1.SetJobStatusRequest.err:type_name -> sdk_v1.Error
	19, // 4: sdk_v1.StageResult.data:type_name -> google.protobuf.Value
	1,  // 5: sdk_v1.SetStageStatusRequest.status:type_name -> sdk_v1.StageStatus
	4,  // 6: sdk_v1.SetStageStatusRequest.err:type_name -> sdk_v1.Error
	8,  // 7: sdk_v1.GetStageResultResponse.result:type_name -> sdk_v1.StageResult
	8,  // 8: sdk_v1.SetStageResultRequest.result:type_name -> sdk_v1.StageResult
	1,  // 9: sdk_v1.GetStageStatusResponse.status:type_name -> sdk_v1.StageStatus
	19, // 10: sdk_v1.Variable.value:type_name -> google.protobuf.Value
	15, // 11: sdk_v1.GetVariableResponse.variable:type_name -> sdk_v1.Variable
	15, // 12: sdk_v1.SetVariableRequest.variable:type_name -> sdk_v1.Variable
	5,  // 13: sdk_v1.AgentService.ExecuteJob:input_type -> sdk_v1.ExecuteJobRequest
	13, // 14: sdk_v1.ManagerService.GetStageStatus:input_type -> sdk_v1.GetStageStatusRequest
	9,  // 15: sdk_v1.ManagerService.SetStageStatus:input_type -> sdk_v1.SetStageStatusRequest
	10, // 16: sdk_v1.ManagerService.GetStageResult:input_type -> sdk_v1.GetStageResultRequest
	12, // 17: sdk_v1.ManagerService.SetStageResult:input_type -> sdk_v1.SetStageResultRequest
	16, // 18: sdk_v1.ManagerService.GetVariable:input_type -> sdk_v1.GetVariableRequest
	18, // 19: sdk_v1.ManagerService.SetVariable:input_type -> sdk_v1.SetVariableRequest
	6,  // 20: sdk_v1.ManagerService.SetJobStatus:input_type -> sdk_v1.SetJobStatusRequest
	7,  // 21: sdk_v1.ManagerService.RegisterHeartbeats:input_type -> sdk_v1.RegisterHeartbeatsRequest
	3,  // 22: sdk_v1.AgentService.ExecuteJob:output_type -> sdk_v1.Void
	14, // 23: sdk_v1.ManagerService.GetStageStatus:output_type -> sdk_v1.GetStageStatusResponse
	3,  // 24: sdk_v1.ManagerService.SetStageStatus:output_type -> sdk_v1.Void
	11, // 25: sdk_v1.ManagerService.GetStageResult:output_type -> sdk_v1.GetStageResultResponse
	3,  // 26: sdk_v1.ManagerService.SetStageResult:output_type -> sdk_v1.Void
	17, // 27: sdk_v1.ManagerService.GetVariable:output_type -> sdk_v1.GetVariableResponse
	3,  // 28: sdk_v1.ManagerService.SetVariable:output_type -> sdk_v1.Void
	3,  // 29: sdk_v1.ManagerService.SetJobStatus:output_type -> sdk_v1.Void
	3,  // 30: sdk_v1.ManagerService.RegisterHeartbeats:output_type -> sdk_v1.Void
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_sdk_proto_init() }
func file_pkg_api_v1_sdk_proto_init() {
	if File_pkg_api_v1_sdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_v1_sdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetJobStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterHeartbeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStageStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStageResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Variable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVariableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_v1_sdk_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_api_v1_sdk_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_v1_sdk_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_api_v1_sdk_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_sdk_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_sdk_proto_enumTypes,
		MessageInfos:      file_pkg_api_v1_sdk_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_sdk_proto = out.File
	file_pkg_api_v1_sdk_proto_rawDesc = nil
	file_pkg_api_v1_sdk_proto_goTypes = nil
	file_pkg_api_v1_sdk_proto_depIdxs = nil
}
