// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/azarc-io/vth-faas-sdk-go/pkg/connector/v1 (interfaces: InboundDescriptor)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	connectorv1 "github.com/azarc-io/vth-faas-sdk-go/pkg/connector/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockInboundDescriptor is a mock of InboundDescriptor interface.
type MockInboundDescriptor struct {
	ctrl     *gomock.Controller
	recorder *MockInboundDescriptorMockRecorder
}

// MockInboundDescriptorMockRecorder is the mock recorder for MockInboundDescriptor.
type MockInboundDescriptorMockRecorder struct {
	mock *MockInboundDescriptor
}

// NewMockInboundDescriptor creates a new mock instance.
func NewMockInboundDescriptor(ctrl *gomock.Controller) *MockInboundDescriptor {
	mock := &MockInboundDescriptor{ctrl: ctrl}
	mock.recorder = &MockInboundDescriptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboundDescriptor) EXPECT() *MockInboundDescriptorMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockInboundDescriptor) Config() connectorv1.Bindable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(connectorv1.Bindable)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockInboundDescriptorMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockInboundDescriptor)(nil).Config))
}

// MessageName mocks base method.
func (m *MockInboundDescriptor) MessageName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageName")
	ret0, _ := ret[0].(string)
	return ret0
}

// MessageName indicates an expected call of MessageName.
func (mr *MockInboundDescriptorMockRecorder) MessageName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageName", reflect.TypeOf((*MockInboundDescriptor)(nil).MessageName))
}

// MessageType mocks base method.
func (m *MockInboundDescriptor) MessageType() connectorv1.MessageType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageType")
	ret0, _ := ret[0].(connectorv1.MessageType)
	return ret0
}

// MessageType indicates an expected call of MessageType.
func (mr *MockInboundDescriptorMockRecorder) MessageType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageType", reflect.TypeOf((*MockInboundDescriptor)(nil).MessageType))
}

// MimeType mocks base method.
func (m *MockInboundDescriptor) MimeType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MimeType")
	ret0, _ := ret[0].(string)
	return ret0
}

// MimeType indicates an expected call of MimeType.
func (mr *MockInboundDescriptorMockRecorder) MimeType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MimeType", reflect.TypeOf((*MockInboundDescriptor)(nil).MimeType))
}

// Name mocks base method.
func (m *MockInboundDescriptor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockInboundDescriptorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockInboundDescriptor)(nil).Name))
}
