---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.62.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor

      - name: "AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Login to Amazon ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: "Create AWS ECR Repo"
        id: ecr
        uses: int128/create-ecr-repository-action@v1.83.0
        with:
          repository: vth-module-runner
          public: true

      - name: 'Releaser'
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.tag.outputs.new_tag }}
          DOCKER_REGISTRY: ${{ steps.ecr.outputs.repository-uri }}
